spring.application.name=javaproject
spring.data.mongodb.database=Map2
spring.data.mongodb.uri=mongodb+srv://ifrah:ifrah-mongodb@cluster0.1e8d3.mongodb.net

#spring.data.mongodb.database=${env.MONGO_DATABASE}
#spring.data.mongodb.database=${MONGO_DATABASE}
#spring.data.mongodb.uri=mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}

spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

server.port=${PORT:8080}